version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mysql:5.7
    container_name: mysqlavitest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: avitest
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
